# Generated by Django 6.0.2 on 2026-03-29 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
