# Generated by Django 6.0.2 on 2026-02-11 21:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('podiums', models.PositiveIntegerField(default=0)),
                ('dnfs', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('base_country', models.CharField(max_length=50)),
                ('engine_supplier', models.CharField(max_length=50)),
                ('team_color', models.CharField(choices=[('#00D7B6', 'Cyan'), ('#003773', 'Navy'), ('#037A68', 'Green'), ('#8F9296', 'Gray'), ('#F47600', 'Papaya'), ('#F282B4', 'Pink'), ('#ED1131', 'Red'), ('#00A0DE', 'Blue')], max_length=15)),
                ('logo_image_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('power_unit', models.CharField(max_length=100)),
                ('is_being_used', models.BooleanField(blank=True, default=False, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='teams.team')),
            ],
        ),
    ]
