# Generated by Django 6.0.2 on 2026-02-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='in_use',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='teams.team'),
        ),
    ]
