# Generated by Django 6.0.2 on 2026-02-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_carmodel_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='in_use',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
