# Generated by Django 6.0.2 on 2026-02-12 20:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('round_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24)])),
                ('weather', models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Mixed', 'Mixed')], max_length=50)),
                ('laps', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_position', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('finishing_position', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('points_awarded', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(25)])),
                ('fastest_lap', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('DNF', 'Did Not Finish'), ('DSQ', 'Disqualified'), ('DNS', 'Did Not Start')], max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='drivers.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.race')),
            ],
            options={
                'unique_together': {('race', 'driver'), ('race', 'finishing_position')},
            },
        ),
        migrations.AddField(
            model_name='race',
            name='drivers',
            field=models.ManyToManyField(related_name='races', through='races.Result', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_track', to='races.track'),
        ),
    ]
