# Generated by Django 6.0.2 on 2026-03-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_result_options_alter_result_unique_together_and_more'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_track', to='tracks.track'),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
