# Generated by Django 6.0.2 on 2026-02-18 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_result_options_alter_race_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='round_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='finishing_position',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
