# Generated by Django 6.0.2 on 2026-02-15 10:51

import django.core.validators
import django.db.models.deletion
import drivers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('nationality', models.CharField(help_text='Enter country code.', max_length=2)),
                ('age', models.PositiveIntegerField()),
                ('rookie_status', models.BooleanField(blank=True, default=False)),
                ('total_points', models.PositiveIntegerField(blank=True, default=0)),
                ('podiums', models.PositiveIntegerField(blank=True, default=0)),
                ('dnfs', models.PositiveIntegerField(blank=True, default=0)),
                ('wins', models.PositiveIntegerField(blank=True, default=0)),
                ('image', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='teams.team', validators=[drivers.validators.AvailableSlotValidator(max_value=2, message='A team can have a maximum of 2 drivers!')])),
            ],
        ),
    ]
