# Generated by Django 6.0.2 on 2026-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rookie_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
