# Generated by Django 6.0.2 on 2026-03-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_nationality_alter_driver_rookie_status'),
        ('teams', '0002_alter_carmodel_in_use_alter_carmodel_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='teams.team'),
        ),
    ]
