# Generated by Django 6.0.2 on 2026-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_rookie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='nationality',
            field=models.CharField(max_length=2),
        ),
    ]
