# Generated by Django 6.0.2 on 2026-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_tracks',
            field=models.ManyToManyField(blank=True, related_name='favorite_tracks', to='tracks.track'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
