# Generated by Django 5.2.12 on 2026-04-06 18:36

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_auth_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), accounts.validators.MaxSizeValidator(max_size=3)]),
        ),
    ]
